# Generated by Django 2.2.3 on 2024-07-30 14:31

import RimborsiApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0047_add_spesa_and_spesamissione'),
    ]

    operations = [
        migrations.AddField(
            model_name='missione',
            name='pernottamenti',
            field=models.ManyToManyField(through='RimborsiApp.SpesaMissione', to='RimborsiApp.Spesa'),
        ),
    ]
