# Generated by Django 2.2.3 on 2024-08-02 20:01

import RimborsiApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0049_edit_spesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missione',
            name='pernottamento',
        ),
    ]
