# Generated by Django 2.2.3 on 2024-08-02 21:24

import RimborsiApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0050_remove_pernottameto_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvegnoMissione',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('RimborsiApp.spesamissione',),
        ),
        migrations.CreateModel(
            name='PernottamentoMissione',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('RimborsiApp.spesamissione',),
        ),
        migrations.AlterField(
            model_name='missione',
            name='pernottamenti',
            field=models.ManyToManyField(related_name='pernottamenti_missioni', through='RimborsiApp.PernottamentoMissione', to='RimborsiApp.Spesa'),
        ),
        migrations.AddField(
            model_name='missione',
            name='convegni',
            field=models.ManyToManyField(related_name='convegni_missioni', through='RimborsiApp.ConvegnoMissione', to='RimborsiApp.Spesa'),
        ),
    ]
