# Generated by Django 2.2.3 on 2024-08-02 22:07

import RimborsiApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0051_add_convegni_missione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missione',
            name='convegno',
        ),
    ]
