# Generated by Django 2.2.3 on 2024-08-02 22:14

import RimborsiApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0052_remove_convegno_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltreSpeseMissione',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('RimborsiApp.spesamissione',),
        ),
        migrations.AddField(
            model_name='missione',
            name='altre_spese',
            field=models.ManyToManyField(related_name='altrespese_missioni', through='RimborsiApp.AltreSpeseMissione', to='RimborsiApp.Spesa'),
        ),
    ]
