# Generated by Django 2.2.3 on 2024-08-03 08:34

import RimborsiApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0055_edit_trasporto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastiMissione',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('RimborsiApp.spesamissione',),
        ),
        migrations.AddField(
            model_name='missione',
            name='pasti',
            field=models.ManyToManyField(related_name='pasti_missioni', through='RimborsiApp.PastiMissione', to='RimborsiApp.Spesa'),
        ),
    ]
