# Generated by Django 2.2.3 on 2024-08-05 08:27

import RimborsiApp.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RimborsiApp', '0057_add_spesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pasti',
            options={'verbose_name': 'Pasto', 'verbose_name_plural': 'Pasti'},
        ),
        migrations.RemoveField(
            model_name='missione',
            name='scontrino',
        ),
    ]
